# Generated by Django 4.2.3 on 2023-07-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('last_battery_level', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PictureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('current_picture_valid_until', models.DateTimeField(blank=True, null=True)),
                ('current_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_picture_for_group', to='selector.picture')),
                ('pictures', models.ManyToManyField(blank=True, related_name='picture_group', to='selector.picture')),
                ('users', models.ManyToManyField(blank=True, related_name='picture_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PictureSet',
        ),
    ]
