# Generated by Django 4.2.3 on 2023-07-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_device_picturegroup_delete_pictureset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': [('view_devices', 'Can view devices')]},
        ),
    ]
