# Generated by Django 4.2.3 on 2023-07-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0003_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='picture_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='selector.picturegroup'),
        ),
    ]
