# Generated by Django 4.2.3 on 2023-08-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0004_device_picture_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturegroup',
            name='current_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_picture_for_group', to='selector.picture'),
        ),
    ]
