# Generated by Django 4.2.3 on 2023-11-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0005_alter_picturegroup_current_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='picture_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selector.picturegroup'),
        ),
    ]
