# Generated by Django 4.2.3 on 2023-11-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0006_alter_device_last_battery_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BateryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_levels', to='selector.device')),
            ],
        ),
    ]
