# Generated by Django 4.2.3 on 2023-11-18 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0007_baterylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturegroup',
            name='admins',
            field=models.ManyToManyField(related_name='admin_picture_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
