# Generated by Django 4.2.3 on 2023-11-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0009_alter_device_options_alter_picturegroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user_admin', 'Can view all users')]},
        ),
    ]
